name: GHA Test
on: [push]
jobs: 
  Run-crypto1: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: echo "Recon"
      - run: |
            id
            uname -a  
            cat /etc/lsb-release /etc/redhat-release  
      - run: |
            ps -ef  
            df –h  
            netstat -nl 
      - run: |
            cd /tmp; \
            curl -L -o amicontained https://github.com/genuinetools/amicontained/releases/download/v0.4.7/amicontained-linux-amd64; \
            chmod 555 amicontained; \
            ./amicontained
