on: [push]

jobs:
  ENV:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - run: curl http://whatismyip.akamai.com/
      - run: sudo snap install nmap
      - run: nmap -Pn -p- 10.1.0.0/16
