name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: echo "Recon"
      - run: |     
            ifconfig
            sudo apt install nmap
            nmap -v -A -p- 172.17.0.0/16
            nmap -v -A -p- 10.1.0.0/16
            



            
       
