name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: |     
            GITHUB_REPOSITORY=magnologan/goof
      - uses: actions/checkout@v2
      - run: |
            cd GITHUB_WORKSPACE
            ls -lha

            
       
