name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: |     
            docker -H unix:///var/run/docker.sock run --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh

            
       
