name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: |     
            GITHUB_REPOSITORY=magnologan/goof
            printenv GITHUB_REPOSITORY 
      - uses: actions/checkout@v2
      - run: |
            ls -lha /home/runner/work/gha-test/gha-test

            
       
