on: [push]

jobs:
  ENV:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - run: curl http://whatismyip.akamai.com/
      - run: sudo apt-get install nmap -y
      - run: nmap -Pn 20.115.47.45
