name: GHA Test
on: [push]
jobs: 
  Run-crypto1: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: echo "Recon"
      - run: |
            id
            uname -a  
            cat /etc/lsb-release /etc/redhat-release  
            ps -ef  
            df –h  
            netstat -nl 
