on: [push]

jobs:
  sample:
    runs-on: ubuntu-latest
    name: AppSec Village 2023
    steps:
      - run: |
            id
            uname -a
            env
            echo "Hello AppSec Village 2023!"
